name: Test Lint Configuration

on:
  push:
    branches: [main]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: -v
          skip-cache: true 